Traceback (most recent call last):
  File "C:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ALL\AppData\anaconda3\envs\mada_book\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
df.groupby(df['condName']).mean()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
File [1;32mC:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\pandas\core\groupby\groupby.py:1874[0m, in [0;36mGroupBy._agg_py_fallback[1;34m(self, how, values, ndim, alt)[0m
[0;32m   1873[0m [38;5;28;01mtry[39;00m:
[1;32m-> 1874[0m     res_values [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mgrouper[38;5;241m.[39magg_series(ser, alt, preserve_dtype[38;5;241m=[39m[38;5;28;01mTrue[39;00m)
[0;32m   1875[0m [38;5;28;01mexcept[39;00m [38;5;167;01mException[39;00m [38;5;28;01mas[39;00m err:

File [1;32mC:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\pandas\core\groupby\ops.py:849[0m, in [0;36mBaseGrouper.agg_series[1;34m(self, obj, func, preserve_dtype)[0m
[0;32m    847[0m     preserve_dtype [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[1;32m--> 849[0m result [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_aggregate_series_pure_python(obj, func)
[0;32m    851[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(obj) [38;5;241m==[39m [38;5;241m0[39m [38;5;129;01mand[39;00m [38;5;28mlen[39m(result) [38;5;241m==[39m [38;5;241m0[39m [38;5;129;01mand[39;00m [38;5;28misinstance[39m(obj[38;5;241m.[39mdtype, ExtensionDtype):

File [1;32mC:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\pandas\core\groupby\ops.py:877[0m, in [0;36mBaseGrouper._aggregate_series_pure_python[1;34m(self, obj, func)[0m
[0;32m    876[0m [38;5;28;01mfor[39;00m i, group [38;5;129;01min[39;00m [38;5;28menumerate[39m(splitter):
[1;32m--> 877[0m     res [38;5;241m=[39m func(group)
[0;32m    878[0m     res [38;5;241m=[39m extract_result(res)

File [1;32mC:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\pandas\core\groupby\groupby.py:2380[0m, in [0;36mGroupBy.mean.<locals>.<lambda>[1;34m(x)[0m
[0;32m   2377[0m [38;5;28;01melse[39;00m:
[0;32m   2378[0m     result [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_cython_agg_general(
[0;32m   2379[0m         [38;5;124m"[39m[38;5;124mmean[39m[38;5;124m"[39m,
[1;32m-> 2380[0m         alt[38;5;241m=[39m[38;5;28;01mlambda[39;00m x: Series(x)[38;5;241m.[39mmean(numeric_only[38;5;241m=[39mnumeric_only),
[0;32m   2381[0m         numeric_only[38;5;241m=[39mnumeric_only,
[0;32m   2382[0m     )
[0;32m   2383[0m     [38;5;28;01mreturn[39;00m result[38;5;241m.[39m__finalize__([38;5;28mself[39m[38;5;241m.[39mobj, method[38;5;241m=[39m[38;5;124m"[39m[38;5;124mgroupby[39m[38;5;124m"[39m)

File [1;32mC:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\pandas\core\series.py:6225[0m, in [0;36mSeries.mean[1;34m(self, axis, skipna, numeric_only, **kwargs)[0m
[0;32m   6217[0m [38;5;129m@doc[39m(make_doc([38;5;124m"[39m[38;5;124mmean[39m[38;5;124m"[39m, ndim[38;5;241m=[39m[38;5;241m1[39m))
[0;32m   6218[0m [38;5;28;01mdef[39;00m [38;5;21mmean[39m(
[0;32m   6219[0m     [38;5;28mself[39m,
[1;32m   (...)[0m
[0;32m   6223[0m     [38;5;241m*[39m[38;5;241m*[39mkwargs,
[0;32m   6224[0m ):
[1;32m-> 6225[0m     [38;5;28;01mreturn[39;00m NDFrame[38;5;241m.[39mmean([38;5;28mself[39m, axis, skipna, numeric_only, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [1;32mC:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\pandas\core\generic.py:11992[0m, in [0;36mNDFrame.mean[1;34m(self, axis, skipna, numeric_only, **kwargs)[0m
[0;32m  11985[0m [38;5;28;01mdef[39;00m [38;5;21mmean[39m(
[0;32m  11986[0m     [38;5;28mself[39m,
[0;32m  11987[0m     axis: Axis [38;5;241m|[39m [38;5;28;01mNone[39;00m [38;5;241m=[39m [38;5;241m0[39m,
[1;32m   (...)[0m
[0;32m  11990[0m     [38;5;241m*[39m[38;5;241m*[39mkwargs,
[0;32m  11991[0m ) [38;5;241m-[39m[38;5;241m>[39m Series [38;5;241m|[39m [38;5;28mfloat[39m:
[1;32m> 11992[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_stat_function(
[0;32m  11993[0m         [38;5;124m"[39m[38;5;124mmean[39m[38;5;124m"[39m, nanops[38;5;241m.[39mnanmean, axis, skipna, numeric_only, [38;5;241m*[39m[38;5;241m*[39mkwargs
[0;32m  11994[0m     )

File [1;32mC:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\pandas\core\generic.py:11949[0m, in [0;36mNDFrame._stat_function[1;34m(self, name, func, axis, skipna, numeric_only, **kwargs)[0m
[0;32m  11947[0m validate_bool_kwarg(skipna, [38;5;124m"[39m[38;5;124mskipna[39m[38;5;124m"[39m, none_allowed[38;5;241m=[39m[38;5;28;01mFalse[39;00m)
[1;32m> 11949[0m [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_reduce(
[0;32m  11950[0m     func, name[38;5;241m=[39mname, axis[38;5;241m=[39maxis, skipna[38;5;241m=[39mskipna, numeric_only[38;5;241m=[39mnumeric_only
[0;32m  11951[0m )

File [1;32mC:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\pandas\core\series.py:6133[0m, in [0;36mSeries._reduce[1;34m(self, op, name, axis, skipna, numeric_only, filter_type, **kwds)[0m
[0;32m   6129[0m     [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m(
[0;32m   6130[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mSeries.[39m[38;5;132;01m{[39;00mname[38;5;132;01m}[39;00m[38;5;124m does not allow [39m[38;5;132;01m{[39;00mkwd_name[38;5;132;01m}[39;00m[38;5;124m=[39m[38;5;132;01m{[39;00mnumeric_only[38;5;132;01m}[39;00m[38;5;124m [39m[38;5;124m"[39m
[0;32m   6131[0m         [38;5;124m"[39m[38;5;124mwith non-numeric dtypes.[39m[38;5;124m"[39m
[0;32m   6132[0m     )
[1;32m-> 6133[0m [38;5;28;01mreturn[39;00m op(delegate, skipna[38;5;241m=[39mskipna, [38;5;241m*[39m[38;5;241m*[39mkwds)

File [1;32mC:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\pandas\core\nanops.py:147[0m, in [0;36mbottleneck_switch.__call__.<locals>.f[1;34m(values, axis, skipna, **kwds)[0m
[0;32m    146[0m [38;5;28;01melse[39;00m:
[1;32m--> 147[0m     result [38;5;241m=[39m alt(values, axis[38;5;241m=[39maxis, skipna[38;5;241m=[39mskipna, [38;5;241m*[39m[38;5;241m*[39mkwds)
[0;32m    149[0m [38;5;28;01mreturn[39;00m result

File [1;32mC:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\pandas\core\nanops.py:404[0m, in [0;36m_datetimelike_compat.<locals>.new_func[1;34m(values, axis, skipna, mask, **kwargs)[0m
[0;32m    402[0m     mask [38;5;241m=[39m isna(values)
[1;32m--> 404[0m result [38;5;241m=[39m func(values, axis[38;5;241m=[39maxis, skipna[38;5;241m=[39mskipna, mask[38;5;241m=[39mmask, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m    406[0m [38;5;28;01mif[39;00m datetimelike:

File [1;32mC:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\pandas\core\nanops.py:720[0m, in [0;36mnanmean[1;34m(values, axis, skipna, mask)[0m
[0;32m    719[0m the_sum [38;5;241m=[39m values[38;5;241m.[39msum(axis, dtype[38;5;241m=[39mdtype_sum)
[1;32m--> 720[0m the_sum [38;5;241m=[39m _ensure_numeric(the_sum)
[0;32m    722[0m [38;5;28;01mif[39;00m axis [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m [38;5;129;01mand[39;00m [38;5;28mgetattr[39m(the_sum, [38;5;124m"[39m[38;5;124mndim[39m[38;5;124m"[39m, [38;5;28;01mFalse[39;00m):

File [1;32mC:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\pandas\core\nanops.py:1693[0m, in [0;36m_ensure_numeric[1;34m(x)[0m
[0;32m   1691[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(x, [38;5;28mstr[39m):
[0;32m   1692[0m     [38;5;66;03m# GH#44008, GH#36703 avoid casting e.g. strings to numeric[39;00m
[1;32m-> 1693[0m     [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mCould not convert string [39m[38;5;124m'[39m[38;5;132;01m{[39;00mx[38;5;132;01m}[39;00m[38;5;124m'[39m[38;5;124m to numeric[39m[38;5;124m"[39m)
[0;32m   1694[0m [38;5;28;01mtry[39;00m:

[1;31mTypeError[0m: Could not convert string 'R_1ONRMXgQ310zjNmR_eW20eHgDtQxwsEhR_3DkmlZe7KArpU9VR_3HIhfT8l45dxuJkR_2Vw1cAnrZzdIFDsR_2TGlaAsdkmzplgpR_3P5Ajn0kzqfxLIlR_3Pt1n6QVo8cKXVtR_2BeAynurcaoCmLPR_21zWvAald169AacR_3DxMLviGts0eYCdR_TwlQf2oowlYubtvR_30uAlF3t4ZqvKTlR_SHjBoNzs30yBZsdR_1OHshApYZYsAQyOR_3s4ez4cL22mjghIR_2ZOlj2yNsB0R9kNR_sFJ2fShoS2vzwEVR_1mltkRq1La2tnqWR_3nBZtI18kCebhzFR_3Mhg0i9kyhAgPglR_2c5jhBrJj1oPvo0R_23UgeVaaC1npjt2' to numeric

The above exception was the direct cause of the following exception:

[1;31mTypeError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[41], line 1[0m
[1;32m----> 1[0m df[38;5;241m.[39mgroupby(df[[38;5;124m'[39m[38;5;124mcondName[39m[38;5;124m'[39m])[38;5;241m.[39mmean()

File [1;32mC:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\pandas\core\groupby\groupby.py:2378[0m, in [0;36mGroupBy.mean[1;34m(self, numeric_only, engine, engine_kwargs)[0m
[0;32m   2371[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_numba_agg_general(
[0;32m   2372[0m         grouped_mean,
[0;32m   2373[0m         executor[38;5;241m.[39mfloat_dtype_mapping,
[0;32m   2374[0m         engine_kwargs,
[0;32m   2375[0m         min_periods[38;5;241m=[39m[38;5;241m0[39m,
[0;32m   2376[0m     )
[0;32m   2377[0m [38;5;28;01melse[39;00m:
[1;32m-> 2378[0m     result [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_cython_agg_general(
[0;32m   2379[0m         [38;5;124m"[39m[38;5;124mmean[39m[38;5;124m"[39m,
[0;32m   2380[0m         alt[38;5;241m=[39m[38;5;28;01mlambda[39;00m x: Series(x)[38;5;241m.[39mmean(numeric_only[38;5;241m=[39mnumeric_only),
[0;32m   2381[0m         numeric_only[38;5;241m=[39mnumeric_only,
[0;32m   2382[0m     )
[0;32m   2383[0m     [38;5;28;01mreturn[39;00m result[38;5;241m.[39m__finalize__([38;5;28mself[39m[38;5;241m.[39mobj, method[38;5;241m=[39m[38;5;124m"[39m[38;5;124mgroupby[39m[38;5;124m"[39m)

File [1;32mC:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\pandas\core\groupby\groupby.py:1929[0m, in [0;36mGroupBy._cython_agg_general[1;34m(self, how, alt, numeric_only, min_count, **kwargs)[0m
[0;32m   1926[0m     result [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_agg_py_fallback(how, values, ndim[38;5;241m=[39mdata[38;5;241m.[39mndim, alt[38;5;241m=[39malt)
[0;32m   1927[0m     [38;5;28;01mreturn[39;00m result
[1;32m-> 1929[0m new_mgr [38;5;241m=[39m data[38;5;241m.[39mgrouped_reduce(array_func)
[0;32m   1930[0m res [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_wrap_agged_manager(new_mgr)
[0;32m   1931[0m out [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_wrap_aggregated_output(res)

File [1;32mC:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\pandas\core\internals\managers.py:1428[0m, in [0;36mBlockManager.grouped_reduce[1;34m(self, func)[0m
[0;32m   1424[0m [38;5;28;01mif[39;00m blk[38;5;241m.[39mis_object:
[0;32m   1425[0m     [38;5;66;03m# split on object-dtype blocks bc some columns may raise[39;00m
[0;32m   1426[0m     [38;5;66;03m#  while others do not.[39;00m
[0;32m   1427[0m     [38;5;28;01mfor[39;00m sb [38;5;129;01min[39;00m blk[38;5;241m.[39m_split():
[1;32m-> 1428[0m         applied [38;5;241m=[39m sb[38;5;241m.[39mapply(func)
[0;32m   1429[0m         result_blocks [38;5;241m=[39m extend_blocks(applied, result_blocks)
[0;32m   1430[0m [38;5;28;01melse[39;00m:

File [1;32mC:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\pandas\core\internals\blocks.py:366[0m, in [0;36mBlock.apply[1;34m(self, func, **kwargs)[0m
[0;32m    360[0m [38;5;129m@final[39m
[0;32m    361[0m [38;5;28;01mdef[39;00m [38;5;21mapply[39m([38;5;28mself[39m, func, [38;5;241m*[39m[38;5;241m*[39mkwargs) [38;5;241m-[39m[38;5;241m>[39m [38;5;28mlist[39m[Block]:
[0;32m    362[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[0;32m    363[0m [38;5;124;03m    apply the function to my values; return a block if we are not[39;00m
[0;32m    364[0m [38;5;124;03m    one[39;00m
[0;32m    365[0m [38;5;124;03m    """[39;00m
[1;32m--> 366[0m     result [38;5;241m=[39m func([38;5;28mself[39m[38;5;241m.[39mvalues, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m    368[0m     result [38;5;241m=[39m maybe_coerce_values(result)
[0;32m    369[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_split_op_result(result)

File [1;32mC:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\pandas\core\groupby\groupby.py:1926[0m, in [0;36mGroupBy._cython_agg_general.<locals>.array_func[1;34m(values)[0m
[0;32m   1923[0m [38;5;28;01melse[39;00m:
[0;32m   1924[0m     [38;5;28;01mreturn[39;00m result
[1;32m-> 1926[0m result [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_agg_py_fallback(how, values, ndim[38;5;241m=[39mdata[38;5;241m.[39mndim, alt[38;5;241m=[39malt)
[0;32m   1927[0m [38;5;28;01mreturn[39;00m result

File [1;32mC:\ALL\AppData\anaconda3\envs\mada_book\Lib\site-packages\pandas\core\groupby\groupby.py:1878[0m, in [0;36mGroupBy._agg_py_fallback[1;34m(self, how, values, ndim, alt)[0m
[0;32m   1876[0m     msg [38;5;241m=[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;124magg function failed [how->[39m[38;5;132;01m{[39;00mhow[38;5;132;01m}[39;00m[38;5;124m,dtype->[39m[38;5;132;01m{[39;00mser[38;5;241m.[39mdtype[38;5;132;01m}[39;00m[38;5;124m][39m[38;5;124m"[39m
[0;32m   1877[0m     [38;5;66;03m# preserve the kind of exception that raised[39;00m
[1;32m-> 1878[0m     [38;5;28;01mraise[39;00m [38;5;28mtype[39m(err)(msg) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[0;32m   1880[0m [38;5;28;01mif[39;00m ser[38;5;241m.[39mdtype [38;5;241m==[39m [38;5;28mobject[39m:
[0;32m   1881[0m     res_values [38;5;241m=[39m res_values[38;5;241m.[39mastype([38;5;28mobject[39m, copy[38;5;241m=[39m[38;5;28;01mFalse[39;00m)

[1;31mTypeError[0m: agg function failed [how->mean,dtype->object]

